services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: my_chat
      POSTGRES_USER: Arseniy
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"